name: CD

on:
  release:
    types: [created]

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mamba & environment
        uses: mamba-org/provision-with-micromamba@v11
      - name: Setup dependencies
        shell: bash -l {0}
        run: |
          sudo apt-get install -y libhdf5-dev inotify-tools libgirepository1.0-dev gstreamer-1.0 gstreamer1.0-tools gstreamer1.0-python3-plugin-loader gir1.2-gstreamer-1.0 gstreamer1.0-clutter-3.0 gstreamer1.0-crystalhd gstreamer1.0-gl gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-pulseaudio gstreamer1.0-x libclutter-gst-3.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 libgstreamer1.0-dev inotify-tools libinotifytools0 build-essential binutils lintian debhelper dh-make devscripts
          pip install tables gobject inotify
          # registering metis plugins
          gst-inspect-1.0
#          GST_DEBUG=6 gst-inspect-1.0 > gst_plugins_list
#          cat gst_plugins_list
         
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -s
      - name: Set release version
        run:
          echo -e "${GITHUB_REF#refs/*/}" > Metis/ver
      - name: Create debian package
        run: | 
          mkdir dist
          cd Metis
          make package
          cp ../*.deb ../dist/
      - name: Upload Release Assets
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./dist/*"]'
