name: CI

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup dependencies
        run: |
          sudo apt-get install -y libhdf5-dev inotify-tools libgirepository1.0-dev
          conda install -c conda-forge gst-plugins-base gst-python gstreamer
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt
      - name: Run tests
        run: pytest tests/ --cov=Metis
      - name: Create package
        run: python setup.py sdist
      - name: Check package
        run: twine check dist/*
      - name: Check manifest 
        run: check-manifest
#  test-windows:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#      - name: Setup dependencies
#        run: |
#          pip install -r requirements/run.txt
#          pip install -r requirements/test.txt
#      - name: Run tests
#        run: pytest tests/ --cov=Semi_ATE
#      - name: Create package
#        run: python setup.py sdist
#      - name: Check package
#        run: twine check dist/*
#      - name: Check manifest 
#        run: check-manifest
