name: CI

on: [push]

env:
  GST_PLUGIN_PATH: /home/runner/work/Metis/Metis/Metis

#          pip install -r requirements/run.txt
#          pip install -r requirements/test.txt
  
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
      - name: Setup dependencies
        run: |
          sudo apt-get install -y libhdf5-dev inotify-tools libgirepository1.0-dev gstreamer-1.0 gstreamer1.0-tools
          conda install -c conda-forge gst-plugins-base==1.20.3 gst-python==1.20.3 gstreamer==1.20.3 pyaml yaml
          pip install gobject PyGObject inotify h5py pytest pytest-cov check-manifest setuptools twine tree tqdm h5py semi-ate-stdf pandas tables pyyaml
          pwd
          ls -la
          conda list 
          pip list
          dpkg -l | grep gst
          echo "========= home cache folder   ==========="
          ls -la ~/.cache
          echo "========= METIS plugins   ==========="
          ls -la /home/runner/work/Metis/Metis/Metis
          echo "========= GST_PLUGIN_PATH ==========="
          echo $GST_PLUGIN_PATH
          echo "========= PWD folder ==========="
          echo $PWD
          gst-inspect-1.0 > gst_plugins_list
          echo "========= home cache folder   ==========="
          ls -la ~/.cache/gstreamer-1.0/
          echo "========= gst plugin list     ==========="
          cat gst_plugins_list
          
      - name: Run tests
        shell: bash
        run: |
          echo "========= GST_PLUGIN_PATH ==========="
          echo $GST_PLUGIN_PATH
          echo "====================================="
          pytest -s
#          bash scripttest.sh
      - name: Create package
        run: python setup.py sdist
      - name: Check package
        run: twine check dist/*
      - name: Check manifest 
        run: check-manifest
#  test-windows:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#      - name: Setup dependencies
#        run: |
#          pip install -r requirements/run.txt
#          pip install -r requirements/test.txt
#      - name: Run tests
#        run: pytest tests/ --cov=Semi_ATE
#      - name: Create package
#        run: python setup.py sdist
#      - name: Check package
#        run: twine check dist/*
#      - name: Check manifest 
#        run: check-manifest
